[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  included_files = [
    "server/templates/certificate_template.docx",
    "server/templates/cards/3.png",
    "server/templates/cards/4.png"
  ]
