import { BrowserRouter, Routes, Route } from 'react-router-dom';
import AttendanceForm from './pages/AttendanceForm';
import AdminRecords from './pages/AdminRecords';
import CreateTrainingSession from './pages/CreateTrainingSession';
import './App.css';

function LandingPage() {
  return (
    <section className="landing-message card">
      <h2>Attendance Sign-In</h2>
      <p>
        Attendance sign-in links are generated by the instructor. Please use
        the link provided for your training session.
      </p>
    </section>
  );
}

function App() {
  return (
    <BrowserRouter>
      <div className="app-shell">
        <header className="top-bar">
          <div className="brand">
            <img
              src="/images/logo.png"
              alt="Attendance Tracker logo"
              className="brand-logo"
            />
            <h1>Attendance Tracker</h1>
          </div>
        </header>

        <main>
          <Routes>
            <Route path="/" element={<LandingPage />} />
            <Route path="/attendance/session/:sessionId" element={<AttendanceForm />} />
            <Route path="/create-session-7392" element={<CreateTrainingSession />} />
            <Route path="/records-7392" element={<AdminRecords />} />
          </Routes>
        </main>
      </div>
    </BrowserRouter>
  );
}

export default App;
